apiVersion: v1
kind: Pod
metadata:
  name: mutate-test
  namespace: amp-test
  labels:
    app: amp-test
    component: api
    mutated: "false"
  annotations:
    amp.txn2.com/example: "mutate"
    amp.txn2.com/delete-me: "this will be removed"
spec:
  volumes:
    - name: existing-vol
      emptyDir: {}
  initContainers:
    - name: existing-init-container
      image: alpine:3.12.0
  containers:
    - name: first-existing-container
      image: alpine:3.12.0
      command: ["tail", "-f", "/dev/null"]
      env:
        - name: EXISTING_ENV_VAR
          value: "here before mutation"
      ports:
        - name: some-port
          containerPort: 7999
      volumeMounts:
        - name: existing-vol
          mountPath: /some-vol
      resources:
        requests:
          cpu: "100m"
          memory: 8Mi
        limits:
          cpu: "200m"
          memory: 64Mi
    - name: second-existing-container
      image: alpine:3.12.0
      command: ["tail", "-f", "/dev/null"]